apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config-tt98bd4h22
  namespace: openedx
  uid: 5c52c243-efb5-4958-bf98-6c451f0fd8e9
  resourceVersion: '51859139'
  creationTimestamp: '2025-01-18T18:16:59Z'
  labels:
    app.kubernetes.io/instance: openedx-zd6XGmYUygmsdAIOtBuNIxp0
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: caddy
    app.kubernetes.io/part-of: openedx
  annotations:
    app.kubernetes.io/version: 19.0.1
data:
  Caddyfile: >-
    # Global configuration

    {

        
        
    }


    # proxy directive snippet (with logging) to be used as follows:

    #

    #     import proxy "containername:port"

    (proxy) {
        log {
            output stdout
            format filter {
                wrap json
                fields {
                    common_log delete
                    request>headers delete
                    resp_headers delete
                    tls delete
                }
            }
        }

        # This will compress requests that matches the default criteria set by Caddy.
        # see https://caddyserver.com/docs/caddyfile/directives/encode
        # for information about the defaults; i.e. how/when this will be applied.
        encode gzip

        reverse_proxy {args.0} {
            header_up X-Forwarded-Port 443
        }

        
    }


    lms.lidoku.com{$default_site_port},
    preview.lms.lidoku.com{$default_site_port} {
        @favicon_matcher {
            path_regexp ^/favicon.ico$
        }
        rewrite @favicon_matcher /theming/asset/images/favicon.ico

        # Limit profile image upload size
        handle_path /api/profile_images/*/*/upload {
            request_body {
                max_size 1MB
            }
        }

        import proxy "lms:8000"

        

        handle_path /* {
            request_body {
                max_size 4MB
            }
        }
    }


    cms.lidoku.com{$default_site_port} {
        @favicon_matcher {
            path_regexp ^/favicon.ico$
        }
        rewrite @favicon_matcher /theming/asset/images/favicon.ico

        import proxy "cms:8000"

        

        handle_path /* {
            request_body {
                max_size 250MB
            }
        }
    }



    meilisearch.lms.lidoku.com{$default_site_port} {
        import proxy "meilisearch:7700"
    }



    apps.lms.lidoku.com{$default_site_port} {
        redir / https://lms.lidoku.com
        request_body {
            max_size 2MB
        }
        import proxy "mfe:8002"
    }
