apiVersion: v1
kind: ConfigMap
metadata:
  name: openedx-config-57k52tff54
  namespace: openedx
  labels:
    app.kubernetes.io/instance: openedx-zd6XGmYUygmsdAIOtBuNIxp0
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: openedx
    app.kubernetes.io/part-of: openedx
  annotations:
    app.kubernetes.io/version: 19.0.1
data:
  cms.env.yml: |-
    SITE_NAME: "cms.lidoku.com"
    BOOK_URL: ""
    LOG_DIR: "/openedx/data/logs"
    LOGGING_ENV: "sandbox"
    OAUTH_OIDC_ISSUER: "https://lms.lidoku.com/oauth2"
    PLATFORM_NAME: "Lindokedx"
    FEATURES:
      
      
      CERTIFICATES_HTML_VIEW: true
      PREVIEW_LMS_BASE: "preview.lms.lidoku.com"
      ENABLE_CSMH_EXTENDED: false
      ENABLE_LEARNER_RECORDS: false
      ENABLE_LIBRARY_INDEX: true
      MILESTONES_APP: true
      ENABLE_PREREQUISITE_COURSES: true
    LMS_ROOT_URL: "https://lms.lidoku.com"
    CMS_ROOT_URL: "https://cms.lidoku.com"
    CMS_BASE: "cms.lidoku.com"
    LMS_BASE: "lms.lidoku.com"
    CONTACT_EMAIL: "jayaram.linux@gmail.com"
    CELERY_BROKER_TRANSPORT: "redis"
    CELERY_BROKER_HOSTNAME: "redis:6379"
    CELERY_BROKER_VHOST: "0"
    CELERY_BROKER_USER: ""
    CELERY_BROKER_PASSWORD: ""
    ALTERNATE_WORKER_QUEUES: "lms"
    ENABLE_COMPREHENSIVE_THEMING: true
    EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST: "smtp"
    EMAIL_PORT: 8025
    EMAIL_USE_TLS: false
    HTTPS: "on"
    LANGUAGE_CODE: "en"
    SESSION_COOKIE_DOMAIN: "cms.lidoku.com"

    SECRET_KEY: "4PusB1OKkVSa17jgaLJZ7yh8"
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    DOC_STORE_CONFIG: null

    XQUEUE_INTERFACE:
      django_auth: null
      url: null
    DATABASES:
      default:
        ENGINE: "django.db.backends.mysql"
        HOST: "mysql"
        PORT: 3306
        NAME: "openedx"
        USER: "openedx"
        PASSWORD: "u17bpI90"
        ATOMIC_REQUESTS: true
        OPTIONS:
          init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
          charset: "utf8mb4"
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
  lms.env.yml: |-
    SITE_NAME: "lms.lidoku.com"
    BOOK_URL: ""
    LOG_DIR: "/openedx/data/logs"
    LOGGING_ENV: "sandbox"
    OAUTH_OIDC_ISSUER: "https://lms.lidoku.com/oauth2"
    PLATFORM_NAME: "Lindokedx"
    FEATURES:
      
      
      CERTIFICATES_HTML_VIEW: true
      PREVIEW_LMS_BASE: "preview.lms.lidoku.com"
      ENABLE_CSMH_EXTENDED: false
      ENABLE_COMBINED_LOGIN_REGISTRATION: true
      ENABLE_GRADE_DOWNLOADS: true
      ENABLE_LEARNER_RECORDS: false
      ENABLE_MOBILE_REST_API: true
      ENABLE_OAUTH2_PROVIDER: true
      ENABLE_PREREQUISITE_COURSES: true
      ENABLE_THIRD_PARTY_AUTH: true
      MILESTONES_APP: true
    LMS_ROOT_URL: "https://lms.lidoku.com"
    CMS_ROOT_URL: "https://cms.lidoku.com"
    CMS_BASE: "cms.lidoku.com"
    LMS_BASE: "lms.lidoku.com"
    CONTACT_EMAIL: "jayaram.linux@gmail.com"
    CELERY_BROKER_TRANSPORT: "redis"
    CELERY_BROKER_HOSTNAME: "redis:6379"
    CELERY_BROKER_VHOST: "0"
    CELERY_BROKER_USER: ""
    CELERY_BROKER_PASSWORD: ""
    ALTERNATE_WORKER_QUEUES: "cms"
    ENABLE_COMPREHENSIVE_THEMING: true
    EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST: "smtp"
    EMAIL_PORT: 8025
    EMAIL_USE_TLS: false
    ACE_ROUTING_KEY: "edx.lms.core.default"
    HTTPS: "on"
    LANGUAGE_CODE: "en"
    SESSION_COOKIE_DOMAIN: "lms.lidoku.com"

    SECRET_KEY: "4PusB1OKkVSa17jgaLJZ7yh8"
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    DOC_STORE_CONFIG: null

    XQUEUE_INTERFACE:
      django_auth: null
      url: null
    DATABASES:
      default:
        ENGINE: "django.db.backends.mysql"
        HOST: "mysql"
        PORT: 3306
        NAME: "openedx"
        USER: "openedx"
        PASSWORD: "u17bpI90"
        ATOMIC_REQUESTS: true
        OPTIONS:
          init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
          charset: "utf8mb4"
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
