apiVersion: v1
kind: ConfigMap
metadata:
  name: openedx-uwsgi-config-5t68c2tcc5
  namespace: openedx
  uid: 5473f292-4998-4b20-a38c-4d197e3a338a
  resourceVersion: '51859156'
  creationTimestamp: '2025-01-18T18:17:01Z'
  labels:
    app.kubernetes.io/instance: openedx-zd6XGmYUygmsdAIOtBuNIxp0
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: openedx
    app.kubernetes.io/part-of: openedx
  annotations:
    app.kubernetes.io/version: 19.0.1
data:
  uwsgi.ini: |+
    [uwsgi]
    static-map = /static=/openedx/staticfiles/
    static-map = /media=/openedx/media/
    http = 0.0.0.0:8000
    buffer-size = 8192
    wsgi-file = $(SERVICE_VARIANT)/wsgi.py
    processes = $(UWSGI_WORKERS)
    thunder-lock = true
    single-interpreter = true
    enable-threads = true
    # Fix 502 errors for closed connections
    http-keepalive = 1
    add-header = Connection: Keep-Alive
    # Better startup/shutdown in docker:
    die-on-term = true
    lazy-apps = false
    need-app = true
    no-defer-accept = true
    # Enable the master process for performance
    master = true
    # Clean up settings
    py-call-osafterfork = true
    vacuum = true

